import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Map from '../components/Map';


export default function Home() {

  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Translink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/dumpling.png" />
      </Head>

      <main className={styles.main}>
        <Image
        alt='translink logo'
        src={"/../public/translink.svg.png"}
        width="200"
        height="100"></Image>
        <h2 style={{fontSize:'50px'}}>Translink Expo Line Stations</h2>
        <Map></Map>
      </main>
      
      <div className={styles.infodiv}>
        <div style={{backgroundColor:"#f2cc8f", borderRadius:"30px", padding:20, width:'80%'}}>
            <h2 style={{
              display:'flex',
              flexDirection:'flex-end',
              fontFamily:'Poppins',
            }}>Expo Line</h2>
            <p>The Expo Line operates two routes:</p>
              <ul>
                <li>Waterfront Station (Downtown Vancouver) to King George Station (Surrey)</li>
                <li>Waterfront Station (Downtown Vancouver) to Production Way–University Station (Burnaby)</li>
              </ul>
            <p>Transfer to the Millennium Line at the following stations:</p>
              <ul>
                <li>Commercial–Broadway Station</li>  
                <li>Lougheed Town Centre Station</li>
                <li>Production Way–University Station</li>
              </ul>
            <p>Use Columbia Station to transfer to and from a train going to either King George or Production Way–University.
            <br/>Use Waterfront Station to transfer to the Canada Line, SeaBus, or West Coast Express.</p>
        </div>
      </div>

      <footer className={styles.footer}>
        <div style={{display:'flex', flexDirection:'row', justifyContent:'center'}}>
          <Image 
          alt='dumpling image'
          src={'/../public/dumpling.png'}
          width='200'
          height='200'></Image>
            
            <div style={{width:'30%', margin:'30px'}}>
              Hi! This is my version of the Translink Expo Line here in Vancouver, BC! Leaftlet React API, created by Volodymyr Agafonkin, was used for this project.
            </div>

            <div>
              <h4 style={{marginTop:'30px'}}>Getting Started</h4>
              <a href="https://www.translink.ca/transit-fares">Transit Fares</a>
              <a href="https://www.translink.ca/schedules-and-maps?page=1">Schedules</a>
              <a href="https://www.translink.ca/rider-guide">Rider Info</a>
              <a href="https://www.translink.ca/alerts">Transit Alerts</a>
            </div>

            <div style={{marginLeft:'30px'}}>
              <h4 style={{marginTop:'30px'}}>Resources</h4>
              <a href="https://www.translink.ca/about-us/customer-service/contact-information">Contact Us</a>
              <a href="https://www.translink.ca/about-us/careers">Career</a>
            </div>

            <div style={{marginLeft:'30px'}}>
              <h4 style={{marginTop:'30px'}}>Contact Us</h4>
              <a>Call us at 604.953.3333</a>
              <a href="https://www.google.com/maps/place/TransLink/@49.2247324,-122.8939064,17z/data=!3m1!4b1!4m5!3m4!1s0x5486765906294161:0x8be44a756edffc2f!8m2!3d49.2247289!4d-122.8917178">
              400-287 Nelson's Ct., <br/> New Westminster, BC V3L0E7</a>
            </div>

        </div>
      </footer>
        

    </div>
    </>
  )
}
